--- Database
SELECT * FROM INFORMATION_SCHEMA.DATABASES;
SELECT * FROM INFORMATION_SCHEMA.REPLICATION_DATABASES;

--- Main Schemas
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA   ORDER BY CATALOG_NAME , SCHEMA_NAME;
SELECT * FROM INFORMATION_SCHEMA.TABLES     ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS    ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME , ORDINAL_POSITION;

--- External Objects
SELECT * FROM INFORMATION_SCHEMA.EXTERNAL_TABLES    ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.FILE_FORMATS;


--- View and SP
SELECT * FROM INFORMATION_SCHEMA.VIEWS      ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.PROCEDURES ORDER BY PROCEDURE_CATALOG , PROCEDURE_SCHEMA , PROCEDURE_NAME;
SELECT * FROM INFORMATION_SCHEMA.FUNCTIONS  ORDER BY FUNCTION_CATALOG , FUNCTION_SCHEMA , FUNCTION_NAME;


--- Billing ******************
SELECT * FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS;

--- Security
SELECT * FROM INFORMATION_SCHEMA.ENABLED_ROLES      ORDER BY ROLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.APPLICABLE_ROLES   ORDER BY ROLE_NAME , GRANTEE;
SELECT * FROM INFORMATION_SCHEMA.OBJECT_PRIVILEGES  ORDER BY GRANTOR , GRANTEE , OBJECT_CATALOG , OBJECT_TYPE , OBJECT_SCHEMA , OBJECT_NAME;
SELECT * FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES   ORDER BY GRANTOR , GRANTEE , OBJECT_CATALOG , OBJECT_TYPE , OBJECT_SCHEMA , OBJECT_NAME;
SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES   ORDER BY GRANTOR , GRANTEE , TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;

--- Relation and constraints 
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS  ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME , CONSTRAINT_TYPE DESC;
--??????
SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS    ORDER BY CONSTRAINT_CATALOG , CONSTRAINT_SCHEMA , CONSTRAINT_NAME;
SELECT * FROM INFORMATION_SCHEMA.SEQUENCES                  ORDER BY SEQUENCE_CATALOG , SEQUENCE_SCHEMA , SEQUENCE_NAME;


--- Stages
SELECT * FROM INFORMATION_SCHEMA.STAGES             ORDER BY STAGE_CATALOG , STAGE_SCHEMA , STAGE_NAME , STAGE_TYPE;

--- Pipeline and Package 
SELECT * FROM INFORMATION_SCHEMA.PIPES              ORDER BY PIPE_CATALOG , PIPE_SCHEMA;
SELECT * FROM INFORMATION_SCHEMA.PACKAGES           ORDER BY PACKAGE_NAME;


--- NOT CLEAR YET ??????????
SELECT * FROM INFORMATION_SCHEMA.LOAD_HISTORY ---???


-------------------------------------------------------------------------------------------------------------------------
--- Admin and Support scripts
SELECT * FROM table(information_schema.query_history_by_session(result_limit =>5));
SELECT * FROM table(information_schema.query_history()) ORDER BY START_TIME DESC;
SELECT * FROM table(information_schema.query_history()) where EXECUTION_STATUS = 'RUNNING' ORDER BY START_TIME DESC;
SELECT * FROM table(information_schema.query_history()) where ERROR_CODE IS NOT NULL;

select * from table(information_schema.copy_history(table_name=>'TBLCLIENT', start_time=> dateadd(hours, -1, current_timestamp())));


select system$clustering_depth('PUBLIC.TBLCLIENT');
select system$clustering_information('PUBLIC.TBLCLIENT', '(BIZFIELD1, BIZFIELD2)');



--- TAG (masking policy)
select system$get_tag_allowed_values('governance.tags.cost_center');
