--- REFERENCE:    https://docs.snowflake.com/en/sql-reference/account-usage#label-account-usage-views


SET FilterDBName = 'SNOWFLAKE_SAMPLE_DATA';

--- Database
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES WHERE DATABASE_NAME = $FilterDBName;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_REPLICATION_USAGE_HISTORY;

--- Main Schemas
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.SCHEMATA  ORDER BY CATALOG_NAME , SCHEMA_NAME;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES     ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMNS    ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME , ORDINAL_POSITION;

--- External Objects
SELECT * FROM INFORMATION_SCHEMA.EXTERNAL_TABLES    ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.FILE_FORMATS;


--- View and SP
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.VIEWS      ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PROCEDURES ORDER BY PROCEDURE_CATALOG , PROCEDURE_SCHEMA , PROCEDURE_NAME;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.FUNCTIONS  ORDER BY FUNCTION_CATALOG , FUNCTION_SCHEMA , FUNCTION_NAME;


--- Object Dependencies / Other Functions
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES



--- Billing ******************
SELECT * FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY;

--- Security
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ROLES             ORDER BY NAME;
SELECT * FROM INFORMATION_SCHEMA.ENABLED_ROLES          ORDER BY ROLE_NAME;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES   ORDER BY NAME;


SELECT * FROM INFORMATION_SCHEMA.APPLICABLE_ROLES   ORDER BY ROLE_NAME , GRANTEE;
SELECT * FROM INFORMATION_SCHEMA.OBJECT_PRIVILEGES  ORDER BY GRANTOR , GRANTEE , OBJECT_CATALOG , OBJECT_TYPE , OBJECT_SCHEMA , OBJECT_NAME;
SELECT * FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES   ORDER BY GRANTOR , GRANTEE , OBJECT_CATALOG , OBJECT_TYPE , OBJECT_SCHEMA , OBJECT_NAME;
SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES   ORDER BY GRANTOR , GRANTEE , TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME;

--- Relation and constraints 
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS  ORDER BY TABLE_CATALOG , TABLE_SCHEMA , TABLE_NAME , CONSTRAINT_TYPE DESC;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_CONSTRAINTS;

--??????
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.REFERENTIAL_CONSTRAINTS;
SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS    ORDER BY CONSTRAINT_CATALOG , CONSTRAINT_SCHEMA , CONSTRAINT_NAME;
SELECT * FROM INFORMATION_SCHEMA.SEQUENCES                  ORDER BY SEQUENCE_CATALOG , SEQUENCE_SCHEMA , SEQUENCE_NAME;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.SEQUENCES;

--- Stages
SELECT * FROM INFORMATION_SCHEMA.STAGES             ORDER BY STAGE_CATALOG , STAGE_SCHEMA , STAGE_NAME , STAGE_TYPE;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STAGES;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STAGE_STORAGE_USAGE_HISTORY;


--- Pipeline and Package 
SELECT * FROM INFORMATION_SCHEMA.PIPES              ORDER BY PIPE_CATALOG , PIPE_SCHEMA;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPES;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY;
SELECT * FROM INFORMATION_SCHEMA.PACKAGES           ORDER BY PACKAGE_NAME;


--- NOT CLEAR YET ??????????
SELECT * FROM INFORMATION_SCHEMA.LOAD_HISTORY; ---???
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY;

-------------------------------------------------------------------------------------------------------------------------
--- Admin and Support scripts
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ACCELERATION_HISTORY; 
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;  --- It has more data like ID fields
SELECT * FROM table(information_schema.query_history_by_session(result_limit =>5));
SELECT * FROM table(information_schema.query_history()) ORDER BY START_TIME DESC;
SELECT * FROM table(information_schema.query_history()) where EXECUTION_STATUS = 'RUNNING' ORDER BY START_TIME DESC;
SELECT * FROM table(information_schema.query_history()) where ERROR_CODE IS NOT NULL;


-----  NOTE :YOU HAVE TO BE IN THE RIGHT DATABASE AND SCHEMA
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY;
select * from table(information_schema.copy_history(table_name=>'MYTABLE', start_time=> dateadd(hours, -1, current_timestamp())));


-----  NOTE :YOU HAVE TO BE IN THE RIGHT DATABASE AND SCHEMA
select system$clustering_depth('PUBLIC.TBLCLIENT');
select system$clustering_information('PUBLIC.TBLCLIENT', '(BIZFIELD1, BIZFIELD2)');



--- TAG (masking policy)
select system$get_tag_allowed_values('governance.tags.cost_center');
